LOG_ROOT = "${HOME}/log"

#==============================================================================
# enable various items for logging. usually used in debugging during
# development, but can be used for edge cases in a production setting.
#
#    ENABLE_DEBUG: true/false - if debug is on a lot of messages about runtime
#                  will get printed to the debug log
#    ENABLE_TRACE: true/false - turns on shell debug (set -vx)
#==============================================================================
ENABLE_DEBUG = "$false"
ENABLE_VERBOSE = "$false"
ENABLE_TRACE = "$false"
ENABLE_PERFORMANCE = "$false"

CONVERSION_PATTERN = "[Time: {0}] [Log: {1}] [Level: {2}] - [Thread: {3}] [File: {4}:{5}] [Method: {6}] - {7}"
TIMESTAMP_OPTS = "dd/mm/yyyy HH:mm:ss"

#==============================================================================
# define the logfile names
#==============================================================================
PERF_LOG_FILE = "performance.log"
ERROR_LOG_FILE = "error.log"
DEBUG_LOG_FILE = "debug.log"
AUDIT_LOG_FILE = "audit.log"
WARN_LOG_FILE = "warn.log"
INFO_LOG_FILE = "info.log"
FATAL_LOG_FILE = "fatal.log"
MONITOR_LOG_FILE = "monitor.log"
DEFAULT_LOG_FILE = "default.log"
