name: PowerShell Scan
on: [push, pull_request]

jobs:
  PSScriptAnalyzer:
    name: PowerShell Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: false
      - name: PowerShell Analyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./ -Recurse -Severity Error -EnableExit
